image:
  file: .gitpod.Dockerfile

tasks:
  - command: minio server ${MINIO_VOLUMES}
    name: MinIO Server
  - command: adminio
    name: AdminIO Server
  - command: |
      sed -i 's/apiMultiBackend = true/apiMultiBackend = false/' ${ADMINIO_UI_PATH}/env.js &&
      sed -i 's/apiBaseUrl = "http:\/\/localhost:8080"/apiBaseUrl = `https:\/\/8080${location.hostname.substr(4)}`/' ${ADMINIO_UI_PATH}/env.js &&
      npx --yes angular-http-server -p ${ADMINIO_UI_PORT} --path ${ADMINIO_UI_PATH}
    name: AdminIO-UI Server
  - command: task install
    name: Terminal

ports:
  - port: 9000
    name: MinIO Server
    onOpen: ignore
  - port: 8080
    name: AdminIO Server
    onOpen: ignore
  - port: 1234
    name: AdminIO-UI Server
    onOpen: open-preview