tasks:
  - command: >
      export DOCKER_COMPOSE_GITPOD_PATH=/tmp/docker-compose.gitpod.yml &&
      cp docker-compose.yml ${DOCKER_COMPOSE_GITPOD_PATH} &&
      sed -i 's/http:\/\/localhost:8080/$API_BASE_URL/g' ${DOCKER_COMPOSE_GITPOD_PATH} &&
      export API_BASE_URL=`gp url 8080` &&
      docker-compose -f ${DOCKER_COMPOSE_GITPOD_PATH} up
  - command: |
      (cd /tmp && brew install hashicorp/tap/terraform go-task/tap/go-task minio-mc)
      go get -v -t -d ./...
      task install
      gp ports await 9000 && gp ports await 8080 && gp ports await 8000
      mc alias set local http://localhost:9000 minio minio123 && echo "MinIO Local Server Stats:" && mc admin info local

ports:
  - port: 9000
    name: MinIO Server
    onOpen: ignore
  - port: 9001
    name: MinIO Server Console
    onOpen: ignore
  - port: 8080
    name: AdminIO Server
    onOpen: ignore
  - port: 8000
    name: AdminIO-UI Server
    onOpen: open-preview

vscode:
  extensions:
    - golang.go
    - hashicorp.terraform
    - streetsidesoftware.code-spell-checker
