tasks:
  - command: >
      export DOCKER_COMPOSE_GITPOD_PATH=/tmp/docker-compose.gitpod.yml &&
      cp docker-compose.yml ${DOCKER_COMPOSE_GITPOD_PATH} &&
      sed -i 's/http:\/\/localhost:8080/$API_BASE_URL/g' ${DOCKER_COMPOSE_GITPOD_PATH} &&
      export API_BASE_URL=`gp url 8080` &&
      docker-compose -f ${DOCKER_COMPOSE_GITPOD_PATH} up
  - env:
      TERRAFORM_VERSION: 0.14.0
    command: >
      export TERRAFORM_DOWNLOAD_FILE_NAME=terraform_${TERRAFORM_VERSION}_linux_amd64.zip &&
      wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${TERRAFORM_DOWNLOAD_FILE_NAME} &&
      unzip ${TERRAFORM_DOWNLOAD_FILE_NAME} &&
      rm ${TERRAFORM_DOWNLOAD_FILE_NAME} &&
      sudo mv terraform /usr/local/bin/terraform &&
      sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin &&
      task install

ports:
  - port: 9000
    name: MinIO Server
    onOpen: ignore
  - port: 8080
    name: AdminIO Server
    onOpen: ignore
  - port: 8000
    name: AdminIO-UI Server
    onOpen: open-preview