version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Security: gosec runs as dedicated step in CI workflow

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Get
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).GetOk

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclusions:
    rules:
      # Exclude linters from running on test files
      - path: _test\.go
        linters:
          - errcheck

      # Exclude errcheck for specific files with heavy SDK usage
      - path: check_config\.go
        linters:
          - errcheck

      - path: import_.*\.go
        linters:
          - errcheck

    paths:
      - third_party$
      - builtin$
      - examples$
