version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2020-11-25T22-36-25Z
    hostname: minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_HTTP_TRACE: /dev/stdout
    command: server /data