package minio

import (
	"context"
	"fmt"
	"math"
	"net/url"
	"path"
	"reflect"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/dustin/go-humanize"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/minio/madmin-go/v4"
	"github.com/minio/minio-go/v7/pkg/replication"
	"github.com/minio/minio-go/v7/pkg/s3utils"
	"github.com/rs/xid"
)

func resourceMinioBucketReplication() *schema.Resource {
	return &schema.Resource{
		CreateContext: minioPutBucketReplication,
		ReadContext:   minioReadBucketReplication,
		UpdateContext: minioPutBucketReplication,
		DeleteContext: minioDeleteBucketReplication,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{
			"bucket": {
				Type:        schema.TypeString,
				Description: "Name of the bucket on which to setup replication rules",
				Required:    true,
				ForceNew:    true,
			},
			"resync_version": {
				Type:        schema.TypeInt,
				Optional:    true,
				Default:     0,
				Description: "Increment this value to trigger a resync of existing objects for all replication rules. Each increment triggers one resync.",
			},
			"last_resync_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "ID of the last resync operation.",
			},
			"rule": {
				Type:        schema.TypeList,
				Description: "Rule definitions",
				Optional:    true,
				Elem:        bucketReplicationRuleResource(),
			},
		},
	}
}

// bucketReplicationRuleResource returns the schema for a single replication rule.
func bucketReplicationRuleResource() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{
			"id": {
				Type:        schema.TypeString,
				Description: "Rule ID generated by MinIO",
				Computed:    true,
			},
			"arn": {
				Type:        schema.TypeString,
				Description: "Rule ARN genrated by MinIO",
				Computed:    true,
			},
			"enabled": {
				Type:        schema.TypeBool,
				Description: "Whether or not this rule is enabled",
				Optional:    true,
				Default:     true,
			},
			"priority": {
				Type:         schema.TypeInt,
				Description:  "Rule priority. If omitted, the inverted index will be used as priority. This means that the first rule definition will have the higher priority",
				Optional:     true,
				ValidateFunc: validation.IntAtLeast(1),
				DiffSuppressFunc: func(k, oldValue, newValue string, d *schema.ResourceData) bool {
					oldVal, _ := strconv.Atoi(oldValue)
					newVal, _ := strconv.Atoi(newValue)
					return oldVal == 0 && newVal == 0 || oldVal == newVal
				},
			},
			"prefix": {
				Type:        schema.TypeString,
				Description: "Bucket prefix object must be in to be syncronised",
				Optional:    true,
				Default:     "",
			},
			"tags": {
				Type:        schema.TypeMap,
				Description: "Tags which objects must have to be syncronised",
				Optional:    true,
				ValidateDiagFunc: validation.AllDiag(
					validation.MapValueMatch(regexp.MustCompile(`^[a-zA-Z0-9-+\-._:/@ ]+$`), ""),
					validation.MapKeyMatch(regexp.MustCompile(`^[a-zA-Z0-9-+\-._:/@ ]+$`), ""),
					validation.MapValueLenBetween(1, 256),
					validation.MapKeyLenBetween(1, 128),
				),
			},
			"delete_replication": {
				Type:        schema.TypeBool,
				Description: "Whether or not to propagate deletion",
				Optional:    true,
			},
			"delete_marker_replication": {
				Type:        schema.TypeBool,
				Description: "Whether or not to synchronise marker deletion",
				Optional:    true,
			},
			"existing_object_replication": {
				Type:        schema.TypeBool,
				Description: "Whether or not to synchronise object created prior the replication configuration",
				Optional:    true,
			},
			"metadata_sync": {
				Type:        schema.TypeBool,
				Description: "Whether or not to synchonise buckets and objects metadata (such as locks). This must be enabled to achieve a two-way replication",
				Optional:    true,
			},
			"target": {
				Type:        schema.TypeList,
				Description: "Bucket prefix",
				MinItems:    1,
				MaxItems:    1,
				Required:    true,
				Elem:        bucketReplicationTargetResource(),
			},
		},
	}
}

// bucketReplicationTargetResource returns the schema for a replication rule target.
func bucketReplicationTargetResource() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{
			"bucket": {
				Type:        schema.TypeString,
				Description: "The name of the existing target bucket to replicate into",
				Required:    true,
			},
			"storage_class": {
				Type:        schema.TypeString,
				Description: "The storage class to use for the object on this target",
				Optional:    true,
			},
			"host": {
				Type:        schema.TypeString,
				Description: "The target host (pair IP/port or domain port). If port is omitted, HTTPS port (or HTTP if unsecure) will be used. This host must be reachable by the MinIO instance itself",
				Required:    true,
			},
			"secure": {
				Type:        schema.TypeBool,
				Description: "Whether to use HTTPS with this target (Recommended). Note that disabling HTTPS will yield Terraform warning for security reason`",
				Optional:    true,
				Default:     true,
			},
			"path_style": {
				Type:         schema.TypeString,
				Description:  "Whether to use path-style or virtual-hosted-syle request to this target (https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access). `auto` allows MinIO to chose automatically the appropriate option (Recommended)`",
				Optional:     true,
				Default:      "auto",
				ValidateFunc: validation.StringInSlice([]string{"on", "off", "auto"}, true),
			},
			"path": {
				Type:        schema.TypeString,
				Description: "Path of the Minio endpoint. This is useful if MinIO API isn't served on at the root, e.g for `example.com/minio/`, the path would be `/minio/`",
				Optional:    true,
			},
			"synchronous": {
				Type:        schema.TypeBool,
				Description: "Use synchronous replication.",
				Optional:    true,
				Computed:    true,
			},
			"syncronous": {
				Type:        schema.TypeBool,
				Description: "Use synchronous replication.",
				Optional:    true,
				Computed:    true,
				Deprecated:  "Use 'synchronous' instead. This attribute will be removed in a future major version.",
			},
			"disable_proxy": {
				Type:        schema.TypeBool,
				Description: "Disable proxy for this target",
				Optional:    true,
				Default:     false,
			},
			"health_check_period": {
				Type:        schema.TypeString,
				Description: "Period where the health of this target will be checked. This must be a valid duration, such as `5s` or `2m`",
				Optional:    true,
				Default:     "30s",
				DiffSuppressFunc: func(k, oldValue, newValue string, d *schema.ResourceData) bool {
					newVal, err := time.ParseDuration(newValue)
					return err == nil && shortDur(newVal) == oldValue
				},
				ValidateFunc: validation.StringMatch(regexp.MustCompile(`^[0-9]+\s?[s|m|h]$`), "must be a valid golang duration"),
			},
			"bandwidth_limit": {
				Type:        schema.TypeString,
				Description: "Maximum bandwidth in byte per second that MinIO can used when syncronysing this target. Minimum is 100MB",
				Optional:    true,
				Default:     "0",
				DiffSuppressFunc: func(k, oldValue, newValue string, d *schema.ResourceData) bool {
					newVal, err := humanize.ParseBytes(newValue)
					return err == nil && humanize.Bytes(newVal) == oldValue
				},
				ValidateDiagFunc: validateReplicationBandwidthLimit,
			},
			"bandwidth_limt": {
				// Deprecated misspelling of bandwidth_limit. Kept in the schema so
				// existing configs do not error at plan time; the legacy value is read
				// via ParseBandwidthLimit in utils.go. Remove in the next major version.
				Type:        schema.TypeString,
				Description: "Deprecated: use 'bandwidth_limit' instead. Will be removed in a future major version.",
				Optional:    true,
				Deprecated:  "Use 'bandwidth_limit' instead. This attribute will be removed in a future major version.",
			},
			"region": {
				Type:        schema.TypeString,
				Description: "Region of the target MinIO. This will be used to generate the target ARN",
				Optional:    true,
			},
			"access_key": {
				Type:         schema.TypeString,
				Description:  "Access key for the replication service account in the target MinIO",
				Required:     true,
				ValidateFunc: validation.StringIsNotEmpty,
			},
			"secret_key": {
				Type:         schema.TypeString,
				Description:  "Secret key for the replication service account in the target MinIO. This is optional so it can be imported but prevent secret update",
				Optional:     true,
				Sensitive:    true,
				ValidateFunc: validation.StringIsNotEmpty,
			},
		},
	}
}

// validateReplicationBandwidthLimit validates the bandwidth_limit target attribute.
func validateReplicationBandwidthLimit(i interface{}, _ cty.Path) (diags diag.Diagnostics) {
	v, ok := i.(string)
	if !ok {
		diags = append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  "expected type of bandwidth_limit to be string",
		})
		return
	}

	if v == "" {
		return
	}

	bandwidth, err := humanize.ParseBytes(v)
	if err != nil {
		diags = append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  fmt.Sprintf("bandwidth_limit must be a positive value. It may use suffixes (k, m, g, ..) '%s'", v),
		})
		return
	}
	// 100 MB (SI) = 100 * 1,000,000 = 100,000,000 bytes
	const minBandwidthLimit = uint64(100000000)
	if bandwidth < minBandwidthLimit {
		diags = append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  fmt.Sprintf("When set, bandwidth_limit must be at least 100MBps '%s'", v),
		})

	}
	return
}

func minioPutBucketReplication(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	bucketReplicationConfig, diags := BucketReplicationConfig(ctx, d, meta)
	replicationConfig := bucketReplicationConfig.ReplicationRules

	if replicationConfig == nil || diags.HasError() {
		return diags
	}

	tflog.Debug(ctx, fmt.Sprintf("S3 bucket: %s, put replication configuration: %v", bucketReplicationConfig.MinioBucket, replicationConfig))

	cfg, err := convertBucketReplicationConfig(ctx, bucketReplicationConfig, replicationConfig)

	if err != nil {
		return NewResourceError(fmt.Sprintf("error generating bucket replication configuration for %q", bucketReplicationConfig.MinioBucket), d.Id(), err)
	}

	err = bucketReplicationConfig.MinioClient.SetBucketReplication(
		ctx,
		bucketReplicationConfig.MinioBucket,
		cfg,
	)

	if err != nil {
		return NewResourceError(fmt.Sprintf("error putting bucket replication configuration for %q", bucketReplicationConfig.MinioBucket), d.Id(), err)
	}

	d.SetId(bucketReplicationConfig.MinioBucket)

	if d.HasChange("resync_version") {
		if resyncDiags := triggerBucketReplicationResync(ctx, bucketReplicationConfig, d); resyncDiags.HasError() {
			return resyncDiags
		}
	}

	return nil
}

// triggerBucketReplicationResync resets replication on every configured target so
// existing objects are re-synchronised.
func triggerBucketReplicationResync(ctx context.Context, bucketReplicationConfig *S3MinioBucketReplication, d *schema.ResourceData) diag.Diagnostics {
	tflog.Debug(ctx, fmt.Sprintf("Triggering replication resync for bucket %s", bucketReplicationConfig.MinioBucket))
	rcfg, err := bucketReplicationConfig.MinioClient.GetBucketReplication(ctx, bucketReplicationConfig.MinioBucket)
	if err != nil {
		return NewResourceError("reading replication config for resync", bucketReplicationConfig.MinioBucket, err)
	}
	for _, rule := range rcfg.Rules {
		if rule.Destination.Bucket != "" {
			info, err := bucketReplicationConfig.MinioClient.ResetBucketReplicationOnTarget(ctx, bucketReplicationConfig.MinioBucket, 0, rule.Destination.Bucket)
			if err != nil {
				return NewResourceError("triggering replication resync", bucketReplicationConfig.MinioBucket, err)
			}
			if len(info.Targets) > 0 {
				_ = d.Set("last_resync_id", info.Targets[0].ResetID)
			}
		}
	}
	return nil
}

func minioReadBucketReplication(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	bucketReplicationConfig, diags := BucketReplicationConfig(ctx, d, meta)

	if diags.HasError() {
		return diags
	}

	client := bucketReplicationConfig.MinioClient
	admclient := bucketReplicationConfig.MinioAdmin
	bucketName := d.Id()

	tflog.Debug(ctx, fmt.Sprintf("S3 bucket replication, read for bucket: %s", bucketName))

	// First, gather the bucket replication config
	rcfg, err := client.GetBucketReplication(ctx, bucketName)
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Unable to fetch bucket replication config for %q: %v", bucketName, err))
		return NewResourceError("reading bucket replication configuration", bucketName, err)
	}

	rules, ruleArnMap, ruleDiags := buildReplicationRuleStates(ctx, bucketName, bucketReplicationConfig, rcfg)
	if ruleDiags.HasError() {
		return ruleDiags
	}

	// Second, we read the remote bucket config
	existingRemoteTargets, err := admclient.ListRemoteTargets(ctx, bucketName, "")
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Unable to fetch existing remote target config for %q: %v", bucketName, err))
		return NewResourceError("reading replication remote target configuration", bucketName, err)
	}

	if len(existingRemoteTargets) != len(rules) {
		return NewResourceError("reading replication configuration", bucketName, fmt.Errorf("inconsistent number of remote target and bucket replication rules (%d != %d)", len(existingRemoteTargets), len(rules)))
	}

	if targetDiags := applyRemoteTargetsToRules(ctx, bucketName, bucketReplicationConfig, existingRemoteTargets, rules, ruleArnMap); targetDiags.HasError() {
		return targetDiags
	}

	if err := d.Set("bucket", d.Id()); err != nil {
		return NewResourceError("setting replication configuration", d.Id(), err)
	}

	if err := d.Set("rule", rules); err != nil {
		return NewResourceError("setting replication configuration", d.Id(), err)
	}

	return diags
}

// buildReplicationRuleStates converts the replication rules returned by MinIO into
// the state representation, preserving the order they have in the configuration.
func buildReplicationRuleStates(ctx context.Context, bucketName string, bucketReplicationConfig *S3MinioBucketReplication, rcfg replication.Config) (rules []map[string]interface{}, ruleArnMap map[string]int, diags diag.Diagnostics) {
	// Reverse index to store rule definition read from Minio to macth the order they have in the IaC. This prevent Terrfaform from try to re-order rule each time
	rulePriorityMap := map[int]int{}
	// Reverse index to store arn and index in the rule set. This is used to match bucket config and remote target order
	ruleArnMap = map[string]int{}

	if bucketReplicationConfig.ReplicationRules != nil {
		for idx, rule := range bucketReplicationConfig.ReplicationRules {
			priority := rule.Priority
			if priority == 0 {
				priority = -len(bucketReplicationConfig.ReplicationRules) + idx
			}
			rulePriorityMap[priority] = idx
		}
	}

	rules = make([]map[string]interface{}, len(rcfg.Rules))

	for idx, rule := range rcfg.Rules {
		var ruleIdx int
		var ok bool
		if ruleIdx, ok = rulePriorityMap[rule.Priority]; !ok {
			ruleIdx = idx
		}
		if _, ok = ruleArnMap[rule.Destination.Bucket]; ok {
			tflog.Warn(ctx, fmt.Sprintf("Conflict detetcted between two rules containing the same ARN for %q: %q", bucketName, rule.Destination.Bucket))
			return nil, nil, NewResourceError("reading replication rules", bucketName, fmt.Errorf("conflict detected between two rules containing the same ARN: %q", rule.Destination.Bucket))
		}
		ruleArnMap[rule.Destination.Bucket] = ruleIdx
		target := map[string]interface{}{
			"storage_class": rule.Destination.StorageClass,
		}
		var priority interface{} = rule.Priority
		if len(bucketReplicationConfig.ReplicationRules) > ruleIdx && rule.Priority == -bucketReplicationConfig.ReplicationRules[ruleIdx].Priority {
			priority = nil
		}
		rules[ruleIdx] = map[string]interface{}{
			"id":                          rule.ID,
			"arn":                         rule.Destination.Bucket,
			"enabled":                     rule.Status == replication.Enabled,
			"priority":                    priority,
			"prefix":                      rule.Prefix(),
			"delete_replication":          rule.DeleteReplication.Status == replication.Enabled,
			"delete_marker_replication":   rule.DeleteMarkerReplication.Status == replication.Enabled,
			"existing_object_replication": rule.ExistingObjectReplication.Status == replication.Enabled,
			"metadata_sync":               rule.SourceSelectionCriteria.ReplicaModifications.Status == replication.Enabled,
		}

		tflog.Debug(ctx, fmt.Sprintf("Rule data for rule#%d is: %+v", ruleIdx, rule))

		if len(rule.Filter.And.Tags) != 0 || rule.Filter.And.Prefix != "" {
			tags := map[string]string{}
			for _, tag := range rule.Filter.And.Tags {
				if tag.IsEmpty() {
					continue
				}
				tags[tag.Key] = tag.Value
			}
			rules[ruleIdx]["tags"] = tags
		} else if rule.Filter.Tag.Key != "" {
			rules[ruleIdx]["tags"] = map[string]string{
				rule.Filter.Tag.Key: rule.Filter.Tag.Value,
			}
		} else {
			rules[ruleIdx]["tags"] = nil
		}

		// During import, there is no rules defined. Furthermore, since it is impossible to read the secret from the API, we
		// default it to an empty string, allowing user to prevent remote changes by also using an empty string or omitting the secret_key
		if len(bucketReplicationConfig.ReplicationRules) > ruleIdx {
			target["secret_key"] = bucketReplicationConfig.ReplicationRules[ruleIdx].Target.SecretKey
		}

		rules[ruleIdx]["target"] = []interface{}{target}
	}

	return rules, ruleArnMap, nil
}

// applyRemoteTargetsToRules enriches the rule state with the remote target details
// read from MinIO's admin API.
func applyRemoteTargetsToRules(ctx context.Context, bucketName string, bucketReplicationConfig *S3MinioBucketReplication, existingRemoteTargets []madmin.BucketTarget, rules []map[string]interface{}, ruleArnMap map[string]int) diag.Diagnostics {
	for _, remoteTarget := range existingRemoteTargets {
		var ruleIdx int
		var ok bool
		var target map[string]interface{}
		if ruleIdx, ok = ruleArnMap[remoteTarget.Arn]; !ok {
			return NewResourceError("reading replication configuration", bucketName, fmt.Errorf("unable to find the remote target configuration for ARN %q", remoteTarget.Arn))
		}
		var targets []interface{}
		if targets, ok = rules[ruleIdx]["target"].([]interface{}); !ok || len(targets) != 1 {
			return NewResourceError("reading replication configuration", bucketName, fmt.Errorf("unable to find the bucket replication configuration associated to ARN %q (rule#%d)", remoteTarget.Arn, ruleIdx))
		}
		if target, ok = targets[0].(map[string]interface{}); !ok || len(target) == 0 {
			return NewResourceError("reading replication configuration", bucketName, fmt.Errorf("unable to extract the target information for the remote target configuration"))
		}

		pathComponent := strings.Split(remoteTarget.TargetBucket, "/")

		tflog.Debug(ctx, fmt.Sprintf("absolute remote target path is %s", remoteTarget.TargetBucket))

		target["bucket"] = pathComponent[len(pathComponent)-1]
		target["host"] = remoteTarget.Endpoint
		target["secure"] = remoteTarget.Secure
		target["path_style"] = remoteTarget.Path
		target["path"] = strings.Join(pathComponent[:len(pathComponent)-1], "/")
		// Runtime auto-migration:
		// - Always write canonical "synchronous".
		// - Also write deprecated "syncronous" so older configs/state continue to work.
		// Both attributes are Optional+Computed, so this does not create perpetual diffs.
		target["synchronous"] = remoteTarget.ReplicationSync
		target["syncronous"] = remoteTarget.ReplicationSync
		target["disable_proxy"] = remoteTarget.DisableProxy
		target["health_check_period"] = shortDur(remoteTarget.HealthCheckDuration)
		var bwUint64 uint64
		if remoteTarget.BandwidthLimit < 0 {
			// Bandwidth limit shouldn't be negative, but handle defensively.
			// Setting to 0 as a safe default.
			tflog.Warn(ctx, fmt.Sprintf("Received negative bandwidth limit (%d) from MinIO, treating as 0", remoteTarget.BandwidthLimit))
			bwUint64 = 0
		} else {
			bwUint64 = uint64(remoteTarget.BandwidthLimit)
		}
		target["bandwidth_limit"] = humanize.Bytes(bwUint64)
		target["region"] = remoteTarget.Region

		target["access_key"] = remoteTarget.Credentials.AccessKey

		tflog.Debug(ctx, fmt.Sprintf("serialised remote target: bucket=%q, host=%q, region=%q, secure=%t, path=%q, path_style=%q, sync=%t, disableProxy=%t", pathComponent[len(pathComponent)-1],
			remoteTarget.Endpoint,
			remoteTarget.Region,
			remoteTarget.Secure,
			strings.Join(pathComponent[:len(pathComponent)-1], "/"),
			remoteTarget.Path,
			remoteTarget.ReplicationSync,
			remoteTarget.DisableProxy))

		// During import, there is no rules defined. Furthermore, since it is impossible to read the secret from the API, we
		// default it to an empty string, allowing user to prevent remote changes by also using an empty string or omitting the secret_key
		if len(bucketReplicationConfig.ReplicationRules) > ruleIdx {
			target["secret_key"] = bucketReplicationConfig.ReplicationRules[ruleIdx].Target.SecretKey
		}

		rules[ruleIdx]["target"] = []interface{}{target}
	}

	return nil
}

func minioDeleteBucketReplication(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	bucketReplicationConfig, diags := BucketReplicationConfig(ctx, d, meta)

	if len(bucketReplicationConfig.ReplicationRules) == 0 && !diags.HasError() {
		tflog.Debug(ctx, fmt.Sprintf("Removing bucket replication for unversioned bucket (%s) from state", d.Id()))
	} else if diags.HasError() {
		return diags
	}

	client := bucketReplicationConfig.MinioClient
	admclient := bucketReplicationConfig.MinioAdmin

	rcfg, err := client.GetBucketReplication(ctx, bucketReplicationConfig.MinioBucket)
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Unable to fetch bucket replication config for %q: %v", bucketReplicationConfig.MinioBucket, err))
		return NewResourceError("reading bucket replication configuration", bucketReplicationConfig.MinioBucket, err)
	}

	tflog.Debug(ctx, fmt.Sprintf("S3 bucket: %s, disabling replication", bucketReplicationConfig.MinioBucket))

	rcfg.Rules = []replication.Rule{}
	err = client.SetBucketReplication(ctx, bucketReplicationConfig.MinioBucket, rcfg)
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Unable to set an empty replication config for %q: %v", bucketReplicationConfig.MinioBucket, err))
		return NewResourceError("disabling bucket replication", bucketReplicationConfig.MinioBucket, err)
	}

	existingRemoteTargets, err := admclient.ListRemoteTargets(ctx, bucketReplicationConfig.MinioBucket, "")
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Unable to fetch existing remote target config for %q: %v", bucketReplicationConfig.MinioBucket, err))
		return NewResourceError("reading replication remote target configuration", bucketReplicationConfig.MinioBucket, err)
	}
	if len(existingRemoteTargets) != 0 {
		return NewResourceError("deleting replication configuration", bucketReplicationConfig.MinioBucket, fmt.Errorf("%d remote targets are still present on the bucket while none are expected", len(existingRemoteTargets)))
	}

	return diags
}

func toEnableFlag(b bool) string {
	if b {
		return "enable"
	}
	return "disable"
}

func convertBucketReplicationConfig(ctx context.Context, bucketReplicationConfig *S3MinioBucketReplication, c []S3MinioBucketReplicationRule) (rcfg replication.Config, err error) {
	client := bucketReplicationConfig.MinioClient
	admclient := bucketReplicationConfig.MinioAdmin

	rcfg, err = client.GetBucketReplication(ctx, bucketReplicationConfig.MinioBucket)
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Unable to fetch bucket replication config for %q: %v", bucketReplicationConfig.MinioBucket, err))
		return
	}

	usedARNs := make([]string, len(c))
	existingRemoteTargets, err := admclient.ListRemoteTargets(ctx, bucketReplicationConfig.MinioBucket, "")
	if err != nil {
		tflog.Warn(ctx, fmt.Sprintf("Unable to fetch existing remote target config for %q: %v", bucketReplicationConfig.MinioBucket, err))
		return
	}

	for i, rule := range c {
		err = s3utils.CheckValidBucketName(rule.Target.Bucket)
		if err != nil {
			tflog.Warn(ctx, fmt.Sprintf("Invalid bucket name for %q: %v", rule.Target.Bucket, err))
			return
		}

		tgtBucket := rule.Target.Bucket
		if rule.Target.Path != "" {
			tgtBucket = path.Clean("./" + rule.Target.Path + "/" + tgtBucket)
		}
		tflog.Debug(ctx, fmt.Sprintf("Full path to target bucket is %s", tgtBucket))

		bktTarget := buildBucketReplicationTarget(rule, tgtBucket)

		var arn string
		arn, err = ensureRemoteTarget(ctx, admclient, bucketReplicationConfig.MinioBucket, rule, bktTarget)
		if err != nil {
			return
		}

		var opts replication.Options
		opts, err = buildReplicationOptions(rule, arn)
		if err != nil {
			return
		}

		if strings.TrimSpace(opts.ID) == "" {
			rule.Id = xid.New().String()
			opts.ID = rule.Id
			opts.Op = replication.AddOption
			tflog.Debug(ctx, fmt.Sprintf("Adding replication option for rule#%d: %v", i, opts))
			err = rcfg.AddRule(opts)
		} else {
			opts.Op = replication.SetOption
			tflog.Debug(ctx, fmt.Sprintf("Editing replication option for rule#%d: %v", i, opts))
			err = rcfg.EditRule(opts)
		}

		if err != nil {
			return
		}
		usedARNs[i] = arn
	}

	for _, existingRemoteTarget := range existingRemoteTargets {
		if !slices.Contains(usedARNs, existingRemoteTarget.Arn) {
			err = admclient.RemoveRemoteTarget(ctx, bucketReplicationConfig.MinioBucket, existingRemoteTarget.Arn)
		}

		if err != nil {
			return
		}
	}

	return
}

// buildBucketReplicationTarget builds the madmin remote target definition for a rule.
func buildBucketReplicationTarget(rule S3MinioBucketReplicationRule, tgtBucket string) *madmin.BucketTarget {
	creds := &madmin.Credentials{AccessKey: rule.Target.AccessKey, SecretKey: rule.Target.SecretKey}
	return &madmin.BucketTarget{
		TargetBucket:        tgtBucket,
		Secure:              rule.Target.Secure,
		Credentials:         creds,
		Endpoint:            rule.Target.Host,
		Path:                rule.Target.PathStyle.String(),
		API:                 "s3v4",
		Type:                madmin.ReplicationService,
		Region:              rule.Target.Region,
		BandwidthLimit:      rule.Target.BandwidthLimit,
		ReplicationSync:     rule.Target.Synchronous,
		DisableProxy:        rule.Target.DisableProxy,
		HealthCheckDuration: rule.Target.HealthCheckPeriod,
	}
}

// ensureRemoteTarget creates or updates the remote target for a rule and returns its ARN.
func ensureRemoteTarget(ctx context.Context, admclient *madmin.AdminClient, bucket string, rule S3MinioBucketReplicationRule, bktTarget *madmin.BucketTarget) (arn string, err error) {
	targets, _ := admclient.ListRemoteTargets(ctx, bucket, string(madmin.ReplicationService))
	tflog.Debug(ctx, fmt.Sprintf("Existing remote targets %q: %v", bucket, targets))

	var existingRemoteTarget *madmin.BucketTarget
	if rule.Arn != "" {
		for i, target := range targets {
			if target.Arn == rule.Arn {
				existingRemoteTarget = &targets[i]
				break
			}
			// At this stage, we could also anticipate already existing remote target failure since endpoint is unique
			// per bucket (https://github.com/minio/minio/blob/master/cmd/bucket-targets.go#L356) but this behavior could change in the future
		}
	}

	if existingRemoteTarget == nil || existingRemoteTarget.ReplicationSync != bktTarget.ReplicationSync {
		if existingRemoteTarget != nil {
			tflog.Debug(ctx, fmt.Sprintf("Synchronous mode change detected (current: %t, new: %t). Re-creating remote target for bucket %q", existingRemoteTarget.ReplicationSync, bktTarget.ReplicationSync, bucket))
		} else {
			tflog.Debug(ctx, fmt.Sprintf("Adding new remote target for bucket %q: %s", bucket, formatBucketTargetForLog(bktTarget)))
		}
		arn, err = admclient.SetRemoteTarget(ctx, bucket, bktTarget)
		if err != nil {
			tflog.Warn(ctx, fmt.Sprintf("Unable to configure remote target for bucket %q and targetBucket=%q at endpoint=%q: %v", bucket,
				bktTarget.TargetBucket,
				bktTarget.Endpoint,
				err))
			return
		}
	} else {
		var remoteTargetUpdate []madmin.TargetUpdateType

		if *existingRemoteTarget.Credentials != *bktTarget.Credentials {
			existingRemoteTarget.Credentials = bktTarget.Credentials
			remoteTargetUpdate = append(remoteTargetUpdate, madmin.CredentialsUpdateType)
		}
		if existingRemoteTarget.ReplicationSync != bktTarget.ReplicationSync {
			existingRemoteTarget.ReplicationSync = bktTarget.ReplicationSync
			remoteTargetUpdate = append(remoteTargetUpdate, madmin.SyncUpdateType)
		}
		if existingRemoteTarget.DisableProxy != bktTarget.DisableProxy {
			existingRemoteTarget.DisableProxy = bktTarget.DisableProxy
			remoteTargetUpdate = append(remoteTargetUpdate, madmin.ProxyUpdateType)
		}
		if existingRemoteTarget.BandwidthLimit != bktTarget.BandwidthLimit {
			existingRemoteTarget.BandwidthLimit = bktTarget.BandwidthLimit
			remoteTargetUpdate = append(remoteTargetUpdate, madmin.BandwidthLimitUpdateType)
		}
		if existingRemoteTarget.HealthCheckDuration != bktTarget.HealthCheckDuration {
			existingRemoteTarget.HealthCheckDuration = bktTarget.HealthCheckDuration
			remoteTargetUpdate = append(remoteTargetUpdate, madmin.HealthCheckDurationUpdateType)
		}
		if existingRemoteTarget.Path != bktTarget.Path {
			existingRemoteTarget.Path = bktTarget.Path
			remoteTargetUpdate = append(remoteTargetUpdate, madmin.PathUpdateType)
		}
		tflog.Debug(ctx, fmt.Sprintf("Editing remote target for bucket %q: %s", bucket, formatBucketTargetForLog(bktTarget)))
		arn, err = admclient.UpdateRemoteTarget(ctx, existingRemoteTarget, remoteTargetUpdate...)
		if err != nil {
			tflog.Warn(ctx, fmt.Sprintf("Unable to update remote target for bucket %q and targetBucket=%q at endpoint=%q: %v", bucket,
				bktTarget.TargetBucket,
				bktTarget.Endpoint,
				err))
			return
		}
	}

	return
}

// buildReplicationOptions builds the replication rule options for a target ARN.
func buildReplicationOptions(rule S3MinioBucketReplicationRule, arn string) (replication.Options, error) {
	tagList := []string{}
	for k, v := range rule.Tags {
		escapedValue, err := url.Parse(v)
		if err != nil {
			return replication.Options{}, err
		}

		tagList = append(tagList, fmt.Sprintf("%s=%s", k, escapedValue.String()))
	}

	return replication.Options{
		TagString:               strings.Join(tagList, "&"),
		IsTagSet:                len(tagList) != 0,
		StorageClass:            rule.Target.StorageClass,
		Priority:                strconv.Itoa(int(math.Abs(float64(rule.Priority)))),
		Prefix:                  rule.Prefix,
		RuleStatus:              toEnableFlag(rule.Enabled),
		ID:                      rule.Id,
		DestBucket:              arn,
		ReplicateDeleteMarkers:  toEnableFlag(rule.DeleteMarkerReplication),
		ReplicateDeletes:        toEnableFlag(rule.DeleteReplication),
		ReplicaSync:             toEnableFlag(rule.MetadataSync),
		ExistingObjectReplicate: toEnableFlag(rule.ExistingObjectReplication),
	}, nil
}

func getBucketReplicationConfig(ctx context.Context, v []interface{}, d *schema.ResourceData) (result []S3MinioBucketReplicationRule, errs diag.Diagnostics) {
	if len(v) == 0 || v[0] == nil {
		return
	}

	result = make([]S3MinioBucketReplicationRule, len(v))
	for i, rule := range v {
		ruleResult, ruleDiags := extractBucketReplicationRule(ctx, i, len(v), rule, d)
		errs = append(errs, ruleDiags...)
		result[i] = ruleResult
	}
	return
}

// extractBucketReplicationRule decodes a single rule from the resource data.
func extractBucketReplicationRule(ctx context.Context, i int, ruleCount int, rule interface{}, d *schema.ResourceData) (result S3MinioBucketReplicationRule, errs diag.Diagnostics) {
	var ok bool
	tfMap, ok := rule.(map[string]interface{})
	if !ok {
		errs = append(errs, diag.Errorf("Unable to extra the rule %d", i)...)
		return
	}
	tflog.Debug(ctx, fmt.Sprintf("rule[%d] contains %v", i, tfMap))

	result.Arn, _ = tfMap["arn"].(string)
	result.Id, _ = tfMap["id"].(string)

	if result.Enabled, ok = tfMap["enabled"].(bool); !ok {
		tflog.Debug(ctx, fmt.Sprintf("rule[%d].enabled omitted. Defaulting to true", i))
		result.Enabled = true
	}

	if result.Priority, ok = tfMap["priority"].(int); !ok || result.Priority == 0 {
		// Since priorities are always positive, we use a negative value to indicate they were automatically generated
		result.Priority = -ruleCount + i
		tflog.Debug(ctx, fmt.Sprintf("rule[%d].priority omitted. Defaulting to index (%d)", i, -result.Priority))
	}

	result.Prefix, _ = tfMap["prefix"].(string)

	if tags, ok := tfMap["tags"].(map[string]interface{}); ok {
		tflog.Debug(ctx, fmt.Sprintf("rule[%d].tags map contains: %v", i, tags))
		tagMap := map[string]string{}
		for k, val := range tags {
			var valOk bool
			tagMap[k], valOk = val.(string)
			if !valOk {
				errs = append(errs, diag.Errorf("rule[%d].tags[%s] value must be a string, not a %s", i, k, reflect.TypeOf(val))...)
			}
		}
		result.Tags = tagMap
	} else {
		errs = append(errs, diag.Errorf("unable to extarct rule[%d].tags of type %s", i, reflect.TypeOf(tfMap["tags"]))...)
	}

	tflog.Debug(ctx, fmt.Sprintf("rule[%d].tags are: %v", i, result.Tags))

	result.DeleteReplication, ok = tfMap["delete_replication"].(bool)
	result.DeleteReplication = result.DeleteReplication && ok
	result.DeleteMarkerReplication, ok = tfMap["delete_marker_replication"].(bool)
	result.DeleteMarkerReplication = result.DeleteMarkerReplication && ok
	result.ExistingObjectReplication, ok = tfMap["existing_object_replication"].(bool)
	result.ExistingObjectReplication = result.ExistingObjectReplication && ok
	result.MetadataSync, ok = tfMap["metadata_sync"].(bool)
	result.MetadataSync = result.MetadataSync && ok

	var targets []interface{}
	if targets, ok = tfMap["target"].([]interface{}); !ok || len(targets) != 1 {
		errs = append(errs, diag.Errorf("Unexpected value type for rule[%d].target. Exactly one target configuration is expected", i)...)
		return
	}
	var target map[string]interface{}
	if target, ok = targets[0].(map[string]interface{}); !ok {
		errs = append(errs, diag.Errorf("Unexpected value type for rule[%d].target. Unable to convert to a usable type", i)...)
		return
	}

	if result.Target.Bucket, ok = target["bucket"].(string); !ok {
		errs = append(errs, diag.Errorf("rule[%d].target.bucket cannot be omitted", i)...)
	}

	result.Target.StorageClass, _ = target["storage_class"].(string)

	if result.Target.Host, ok = target["host"].(string); !ok {
		errs = append(errs, diag.Errorf("rule[%d].target.host cannot be omitted", i)...)
	}

	result.Target.Path, _ = target["path"].(string)
	result.Target.Region, _ = target["region"].(string)

	if result.Target.AccessKey, ok = target["access_key"].(string); !ok {
		errs = append(errs, diag.Errorf("rule[%d].target.access_key cannot be omitted", i)...)
	}

	if result.Target.SecretKey, ok = target["secret_key"].(string); !ok {
		errs = append(errs, diag.Errorf("rule[%d].target.secret_key cannot be omitted", i)...)
	}

	if result.Target.Secure, ok = target["secure"].(bool); !result.Target.Secure || !ok {
		errs = append(errs, diag.Diagnostic{
			Severity: diag.Warning,
			Summary:  fmt.Sprintf("rule[%d].target.secure is false. It is unsafe to use bucket replication over HTTP", i),
		})
	}

	result.Target.Synchronous = resolveReplicationTargetSync(d, i, target)

	result.Target.DisableProxy, ok = target["disable_proxy"].(bool)
	result.Target.DisableProxy = result.Target.DisableProxy && ok

	var err error
	bandwidth, ok, parseDiags := ParseBandwidthLimit(ctx, target)
	if len(parseDiags) > 0 {
		errs = append(errs, diag.Errorf("rule[%d].target.bandwidth_limit is invalid. Make sure to use k, m, g as prefix only", i)...)
	}

	if ok {
		var bwLimit int64
		if bandwidth > uint64(math.MaxInt64) {
			tflog.Warn(ctx, fmt.Sprintf("Configured bandwidth limit (%d) exceeds maximum supported value (%d), clamping.", bandwidth, int64(math.MaxInt64)))
			bwLimit = math.MaxInt64 // Clamp to max int64 if overflow would occur
		} else {
			bwLimit = int64(bandwidth)
		}
		result.Target.BandwidthLimit = bwLimit // Safe conversion
	}

	var healthcheckDuration string
	if healthcheckDuration, ok = target["health_check_period"].(string); ok {
		result.Target.HealthCheckPeriod, err = time.ParseDuration(healthcheckDuration)
		if err != nil {
			tflog.Warn(ctx, fmt.Sprintf("invalid healthcheck value %q: %v", result.Target.HealthCheckPeriod, err))
			errs = append(errs, diag.Errorf("rule[%d].target.health_check_period is invalid. Make sure to use a valid golang time duration notation", i)...)
		}
	}

	var pathstyle string
	pathstyle, _ = target["path_style"].(string)
	switch strings.TrimSpace(strings.ToLower(pathstyle)) {
	case "on":
		result.Target.PathStyle = S3PathStyleOn
	case "off":
		result.Target.PathStyle = S3PathStyleOff
	default:
		if pathstyle != "auto" && pathstyle != "" {
			errs = append(errs, diag.Diagnostic{
				Severity: diag.Warning,
				Summary:  fmt.Sprintf("rule[%d].target.path_style must be \"on\", \"off\" or \"auto\". Defaulting to \"auto\"", i),
			})
		}
		result.Target.PathStyle = S3PathStyleAuto
	}

	return
}

// resolveReplicationTargetSync determines the synchronous replication setting for a
// target, preferring the canonical "synchronous" attribute over the deprecated
// "syncronous" one.
func resolveReplicationTargetSync(d *schema.ResourceData, i int, target map[string]interface{}) bool {
	// Prefer "synchronous" over deprecated "syncronous".
	// Note: GetRawConfig returns null during Read operations (when reading from state),
	// so we fall back to the decoded value from the target map in that case.
	rawConfig := d.GetRawConfig()
	if !rawConfig.IsNull() {
		rulesAttr := rawConfig.GetAttr("rule")
		if !rulesAttr.IsNull() && rulesAttr.IsKnown() && rulesAttr.LengthInt() > i {
			ruleVal := rulesAttr.Index(cty.NumberIntVal(int64(i)))
			if !ruleVal.IsNull() && ruleVal.IsKnown() {
				targetAttr := ruleVal.GetAttr("target")
				if !targetAttr.IsNull() && targetAttr.IsKnown() && targetAttr.LengthInt() > 0 {
					targetVal := targetAttr.Index(cty.NumberIntVal(0))
					if !targetVal.IsNull() && targetVal.IsKnown() {
						syncAttr := targetVal.GetAttr("synchronous")
						if !syncAttr.IsNull() && syncAttr.IsKnown() {
							return syncAttr.True()
						}
						// Fall back to deprecated "syncronous" if "synchronous" not set
						syncronousAttr := targetVal.GetAttr("syncronous")
						if !syncronousAttr.IsNull() && syncronousAttr.IsKnown() {
							return syncronousAttr.True()
						}
					}
				}
			}
		}
	}
	// Fall back to decoded value from state when raw config is not available (e.g., during Read)
	if v, ok := target["synchronous"].(bool); ok {
		return v
	}
	if v, ok := target["syncronous"].(bool); ok {
		return v
	}
	return false
}

func formatBucketTargetForLog(t *madmin.BucketTarget) string {
	return fmt.Sprintf("targetBucket=%q, endpoint=%q, region=%q, secure=%t, path=%q, bandwidthLimit=%d, sync=%t, disableProxy=%t, healthCheckDuration=%s",
		t.TargetBucket,
		t.Endpoint,
		t.Region,
		t.Secure,
		t.Path,
		t.BandwidthLimit,
		t.ReplicationSync,
		t.DisableProxy,
		t.HealthCheckDuration,
	)
}
